name: Deploy Stats Service

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/irelis-module-ia:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/irelis-module-ia:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/irelis-module-ia:latest

      - name: Stop old container
        run: docker rm -f irelis-module-ia || true

      - name: Run new container
        run: |
          docker run -d \
            --name irelis-module-ia \
            -p 4000:4000 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            ${{ secrets.DOCKER_USERNAME }}/irelis-module-ia:latest
